name: Build & Push Docker Image

on:
  push:
    branches: [ master ]  # Or 'main' if your repo uses that

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/ai-learnings:latest MLOps/Docker

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:latest

